# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 13:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date publish',
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 17, 13, 4, 11, 786652, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
